name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./backend.Tests/backend.Tests.csproj

      - name: Build
        run: dotnet build ./backend.Tests/backend.Tests.csproj --no-restore

      - name: Test
        run: dotnet test ./backend.Tests/backend.Tests.csproj --no-build --verbosity normal
