name: Frontend ESLint

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-eslint.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-eslint.yml'

jobs:
  eslint:
    name: Run ESLint (frontend)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      # Ensure ESLint and SARIF formatter are available even if not listed in package.json
      # Also ensure a compatible TypeScript is present for @typescript-eslint/parser
      - name: Install ESLint + SARIF formatter (no-save)
        run: |
          npm install --no-save eslint@^9 @microsoft/eslint-formatter-sarif@^3 typescript@^5

      - name: Run ESLint and generate SARIF
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: 'true'
        run: |
          npx eslint src \
            --ext .js,.jsx,.ts,.tsx \
            --format @microsoft/eslint-formatter-sarif \
            --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: frontend/eslint-results.sarif
